// HashMeVersion.hpp
// Generated by CMake

namespace HashMe
{
const int32_t HM_VERSION_MAJOR = @HashMe_VERSION_MAJOR@;
const int32_t HM_VERSION_MINOR = @HashMe_VERSION_MINOR@;
const int32_t HM_VERSION_PATCH = @HashMe_VERSION_PATCH@;
const std::string HM_VERSION_STRING = "v@HashMe_VERSION@";

const std::string HM_APP_CMAKE_NAME = "@PROJECT_NAME@";
const std::string HM_APP_CMAKE_DESCRIPTION = "@HashMe_DESCRIPTION@";
};
